spring.application.name=e2eeChat
server.port=8080

#Mongo DB config
#spring.data.mongodb.uri=mongodb://localhost:27017/e2eeChatDb

spring.data.mongodb.uri=mongodb+srv://ar_rahul:ar_rahul@cluster0.xp1svyf.mongodb.net/e2eeChatDb?retryWrites=true&w=majority

jwt.secret=SFl/JTBg+xk7fLR5VETDKgDnm6lOh+MWoc5UK6thcJo=